// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPITnF9On6Q55zDheO5C36G2ZtkptF_BI',
    appId: '1:212413751533:web:72c9b5ca9327854d22ece4',
    messagingSenderId: '212413751533',
    projectId: 'ibuy-bym',
    authDomain: 'ibuy-bym.firebaseapp.com',
    storageBucket: 'ibuy-bym.appspot.com',
    measurementId: 'G-ZWQ4PQ1CE0',
  );
  static const FirebaseOptions android = FirebaseOptions(
  apiKey: "AIzaSyAPITnF9On6Q55zDheO5C36G2ZtkptF_BI",
  appId: "1:212413751533:web:72c9b5ca9327854d22ece4",
  messagingSenderId: "212413751533",
  projectId: "ibuy-bym",
  storageBucket: "ibuy-bym.appspot.com",
);

}